# Generated by Django 5.1.3 on 2024-11-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_type',
            new_name='type',
        ),
    ]
